// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubdmzofdhqjgoejoopxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViZG16b2ZkaHFqZ29lam9vcHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTQ0NjksImV4cCI6MjA3MDMzMDQ2OX0.e4lNWehKJb4YWCl1YcxHQOK5m7Zef-gzZ8hID7g78dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});